# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://registry.verra.org/app/search/VCS")
    self.driver.set_window_size(2138, 1415)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) .text-uppercase").click()
    dropdown = self.driver.find_element(By.ID, "search_sel_proj_type")
    dropdown.find_element(By.XPATH, "//option[. = 'Energy industries (renewable/non-renewable sources)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#search_sel_proj_type > option:nth-child(6)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#search_sel_proj_type > option:nth-child(6)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Tongyi CMM Power Generation Project").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) a").click()
  
